### ISSUE TITLE
Infinite loop processing unhandledRejection when filter applied

### ISSUE THREAD

**Issue by andykellr** [airbrake/airbrake-js#425]
We recently upgrade to `airbrake-js` after a long time of using the old deprecated library. We just deployed yesterday and noticed the following issue, which is a major problem for us. I don't have time at the moment to write up better instructions to reproduce this or offer a PR.

The basic issue is this:
1) trigger an unhandledRejection somewhere in the code
2) airbrake detects this and attempts to notify
3) filters are processed and one returns null to filter the message
4) the Promise is rejected, causing an unhandledRejection (goto 2)

Here's some sample code:

```
const AirbrakeClient = require('airbrake-js');

const AIRBRAKE_PROJECT_ID = '000000';
const AIRBRAKE_PROJECT_KEY = '00000000000000000000000000000000';

const airbrake = new AirbrakeClient({
  projectId: AIRBRAKE_PROJECT_ID,
  projectKey: AIRBRAKE_PROJECT_KEY,
});

airbrake.addFilter(notice => null);

process.on('unhandledRejection', r => {
  console.log('-');
});

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function wait() {
  while (true) {
    console.log('.');
    await sleep(1000);
  }
}

async function reject() {
  await sleep(2000);
  console.log('Triggering an unhandledRejection');
  return Promise.reject(new Error('This will not be handled'));
}

reject();
wait();
```

When you run, you'll see two dots from the wait and then dashes from the loop of unhandledRejections.

Here is a diff of the PR I would submit if I had more time:

```
diff --git a/src/client.ts b/src/client.ts
index b3e2ea6..ba6642a 100644
--- a/src/client.ts
+++ b/src/client.ts
@@ -181,8 +181,8 @@ class Client {
         for (let filter of this.filters) {
             let r = filter(notice);
             if (r === null) {
-                let reason = new Error('airbrake: error is filtered');
-                return Promise.reject(reason);
+                // airbrake was filtered. this is a feature, not an error.
+                return Promise.resolve({ errors: [] });
             }
             notice = r;
         }
diff --git a/src/historian.ts b/src/historian.ts
index b607198..87355ba 100644
--- a/src/historian.ts
+++ b/src/historian.ts
@@ -67,7 +67,8 @@ export default class Historian {
                 this.notify(err).then(exit).catch(exit);
             });
             p.on('unhandledRejection', (reason: Error, _p) => {
-                this.notify(reason);
+                // ignore notify errors which will just cause more unhandledRejection errors
+                this.notify(reason).catch(_ => { });
             });
         }
```

**Comment by andykellr** [comment]
The patch may fix the issue, but it's really not a great solution. It can still trigger an unhandledRejection for every filtered airbrake. Filtering is a standard feature that should not trigger Errors.

You might want to mention this issue in the readme. You example code:

```var promise = airbrake.notify(`user id=${user_id} not found`);
promise.then(function(notice) {
  console.log('notice id', notice.id);
});
promise.catch(function(err) {
  console.log('airbrake error', err);
});```

prints this for every filtered error:

```airbrake error Error: airbrake: error is filtered
    at Client../src/client.ts.Client.notify (/Users/andy/src/git/airbrake-js-example/node_modules/airbrake-js/dist/client.js:1153:30)
    at reject (/Users/andy/src/git/airbrake-js-example/index.js:31:26)
    at <anonymous>
```

**Comment by vmihailenco** [comment]
It is not obvious, but I think you must use chaining to make it work properly:

```js
var promise = airbrake.notify(`user id=${user_id} not found`)
  .then(function(notice) {
    console.log('notice id', notice.id);
  })
  .catch(function(err) {
    console.log('airbrake error', err);
  });
```

And it is not airbrake-js specific - try this:

```js
function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function wait() {
  while (true) {
    console.log('.');
    await sleep(1000);
  }
}

process.on('unhandledRejection', r => {
  console.log('unhandledRejection', r);
});

var promise = Promise.reject('rejected');
promise.then(function() { console.log('all good'); })
promise.catch(function(err) { console.log('catched error', err); });

wait();
```

**Comment by ndrake** [comment]
Even when chaining the then/catch I still get the error:

```
client.js:1153 Uncaught (in promise) Error: airbrake: error is filtered
    at Client../src/client.ts.Client.notify (client.js:1153)
    at Historian../src/historian.ts.Historian.notifyNotifiers (client.js:1573)
    at Historian../src/historian.ts.Historian.notify (client.js:1561)
    at Historian../src/historian.ts.Historian.onerror (client.js:1584)
    at Historian.window.onerror (client.js:1501)
```

I'm doing this in my code:

```
airbrake.notify(errorData).then((notice) => {
    console.log(notice);
}).catch((err) => {
    console.log(err);
});
```
