### ISSUE TITLE
unhandledRejection behaves differently than uncaughtException

### ISSUE THREAD

**Issue by ftrimble** [airbrake/airbrake-js#455]
On 1.4.2, I've built out a simple test case that demonstrates the difference between these two behaviors:
test.js:
```
'use strict';

const airbrake = require('airbrake-js');

async function test() {
  Promise.reject(new Error('test'));
}
test();
```
output:
```
forest@forest-ThinkPad-X1-Carbon-4th:~/workspace/blend-utils$ node test.js 
forest@forest-ThinkPad-X1-Carbon-4th:~/workspace/blend-utils$ echo $?
0
```
whereas the unhandled exception one works fine:
```
'use strict';

const async = require('async');

async.waterfall([
  cb => { throw new Error('test'); },
], process.exit);
```

```
forest@forest-ThinkPad-X1-Carbon-4th:~/workspace/blend-utils$ node test.js 
/home/forest/workspace/blend-utils/test.js:6
  cb => { throw new Error('test'); },
          ^

Error: test
    at async.waterfall.cb (/home/forest/workspace/blend-utils/test.js:6:17)
    at nextTask (/home/forest/workspace/blend-utils/node_modules/async/dist/async.js:5324:14)
    at Object.waterfall (/home/forest/workspace/blend-utils/node_modules/async/dist/async.js:5334:5)
    at Object.<anonymous> (/home/forest/workspace/blend-utils/test.js:5:7)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
```

Note that i can add my own unhandled rejection handler to mitigate this issue, but this becomes a nuisance if you're transitively `require`ing `airbrake-js` in scripts and many different locations, since every different entry point needs a new `unhandledRejection` handler.

```
const airbrake = require('airbrake-js');

process.on('unhandledRejection', err => {
  console.log(err);
  process.exit(1);
});

async function test() {
  Promise.reject(new Error('test'));
}
test();
```
output:
```
forest@forest-ThinkPad-X1-Carbon-4th:~/workspace/blend-utils$ node test.js 
Error: test
    at test (/home/forest/workspace/blend-utils/test.js:18:18)
    at Object.<anonymous> (/home/forest/workspace/blend-utils/test.js:20:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

this is close to the behavior if aibrake isn't required at all:
```
async function test() {
  Promise.reject(new Error('test'));
}
test();
```
output:
```
forest@forest-ThinkPad-X1-Carbon-4th:~/workspace/blend-utils$ node test.js 
(node:11969) UnhandledPromiseRejectionWarning: Error: test
    at test (/home/forest/workspace/blend-utils/test.js:18:18)
    at Object.<anonymous> (/home/forest/workspace/blend-utils/test.js:20:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
(node:11969) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11969) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It looks like this was handled for exceptions in some combination of https://github.com/airbrake/airbrake-js/pull/391 and https://github.com/airbrake/airbrake-js/commit/0b3c8705720c09276eaa1584a1d12579dcc0ef78 - can we make sure both of these are getting the same support here? Let me know if you'd be interested in me opening a pr.

**Comment by vmihailenco** [comment]
Do you suggest we log a message and exit or just log a message? Or I misunderstand this?

**Comment by ftrimble** [comment]
ideally it should just be the same behavior as uncaughtException. Logging at the very least would be helpful.
