### ISSUE TITLE
ReferenceError: fetch is not defined

### ISSUE THREAD

**Issue by penngrove** [airbrake/airbrake-js#501]
I'm getting this in console with latest airbrake-js

`ReferenceError: fetch is not defined
    at Client.request [as requester] (/home/menendez/git/indexing-service/node_modules/airbrake-js/dist/webpack:/airbrakeJs.Client/src/http_req/fetch.ts:19:5)
    at Client../src/client.ts.Client.sendNotice (/home/menendez/git/indexing-service/node_modules/airbrake-js/dist/webpack:/airbrakeJs.Client/src/client.ts:214:21)
    at Client../src/client.ts.Client.notify (/home/menendez/git/indexing-service/node_modules/airbrake-js/dist/webpack:/airbrakeJs.Client/src/client.ts:200:21)
    at Historian../src/historian.ts.Historian.notifyNotifiers (/home/menendez/git/indexing-service/node_modules/airbrake-js/dist/webpack:/airbrakeJs.Client/src/historian.ts:142:36)
    at Historian../src/historian.ts.Historian.notify (/home/menendez/git/indexing-service/node_modules/airbrake-js/dist/webpack:/airbrakeJs.Client/src/historian.ts:128:25)
    at process.<anonymous> (/home/menendez/git/indexing-service/node_modules/airbrake-js/dist/webpack:/airbrakeJs.Client/src/historian.ts:67:22)
    at process.emit (events.js:187:15)
    at process.EventEmitter.emit (domain.js:442:20)
    at process.emit (/home/menendez/git/indexing-service/node_modules/ts-node/node_modules/source-map-support/source-map-support.js:461:21)
    at process._fatalException (internal/bootstrap/node.js:491:27)
`

**Comment by penngrove** [comment]
This is related to the express makeMiddleware

**Comment by vmihailenco** [comment]
Which version do you use? We have fixed something similar in v1.6.1

**Comment by penngrove** [comment]
It still is 1.6.1

/home/menendez/git/indexing-service/node_modules/airbrake-js/dist/client.js:2414
    return fetch(req.url, opt).then(function (resp) {
    ^

ReferenceError: fetch is not defined
    at Client.request [as requester] (/home/menendez/git/indexing-service/node_modules/airbrake-js/dist/webpack:/airbrakeJs.Client/src/http_req/fetch.ts:19:5)
    at Client../src/client.ts.Client.sendNotice (/home/menendez/git/indexing-service/node_modules/airbrake-js/dist/webpack:/airbrakeJs.Client/src/client.ts:214:21)
    at Client../src/client.ts.Client.notify (/home/menendez/git/indexing-service/node_modules/airbrake-js/dist/webpack:/airbrakeJs.Client/src/client.ts:200:21)
    at Historian../src/historian.ts.Historian.notifyNotifiers (/home/menendez/git/indexing-service/node_modules/airbrake-js/dist/webpack:/airbrakeJs.Client/src/historian.ts:142:36)
    at Historian../src/historian.ts.Historian.notify (/home/menendez/git/indexing-service/node_modules/airbrake-js/dist/webpack:/airbrakeJs.Client/src/historian.ts:128:25)
    at process.<anonymous> (/home/menendez/git/indexing-service/node_modules/airbrake-js/dist/webpack:/airbrakeJs.Client/src/historian.ts:67:22)
    at process.emit (events.js:187:15)
    at process.EventEmitter.emit (domain.js:442:20)
    at process.emit (/home/menendez/git/indexing-service/node_modules/ts-node/node_modules/source-map-support/source-map-support.js:461:21)
    at process._fatalException (internal/bootstrap/node.js:491:27)

**Comment by penngrove** [comment]
I tried 1.6.2 and I still got the issue:

`/home/menendez/git/indexing-service/node_modules/airbrake-js/dist/client.js:1938
    return fetch(req.url, opt).then(function (resp) {
           ^

TypeError: fetch is not a function
    at Client.request [as requester] (/home/menendez/git/indexing-service/node_modules/airbrake-js/dist/webpack:/airbrakeJs.Client/src/http_req/fetch.ts:19:12)
    at Client../src/client.ts.Client.sendNotice (/home/menendez/git/indexing-service/node_modules/airbrake-js/dist/webpack:/airbrakeJs.Client/src/client.ts:214:21)
    at Client../src/client.ts.Client.notify (/home/menendez/git/indexing-service/node_modules/airbrake-js/dist/webpack:/airbrakeJs.Client/src/client.ts:200:21)
    at Historian../src/historian.ts.Historian.notifyNotifiers (/home/menendez/git/indexing-service/node_modules/airbrake-js/dist/webpack:/airbrakeJs.Client/src/historian.ts:142:36)
    at Historian../src/historian.ts.Historian.notify (/home/menendez/git/indexing-service/node_modules/airbrake-js/dist/webpack:/airbrakeJs.Client/src/historian.ts:128:25)
    at process.<anonymous> (/home/menendez/git/indexing-service/node_modules/airbrake-js/dist/webpack:/airbrakeJs.Client/src/historian.ts:67:22)
    at process.emit (events.js:187:15)
    at process.EventEmitter.emit (domain.js:442:20)
    at process.emit (/home/menendez/git/indexing-service/node_modules/ts-node/node_modules/source-map-support/source-map-support.js:461:21)
    at process._fatalException (internal/bootstrap/node.js:491:27)
[nodemon] app crashed - waiting for file changes before starting...
`

**Comment by penngrove** [comment]
Should you have used node-fetch instead of cross-fetch/polyfill ?

**Comment by penngrove** [comment]
I did include cross-fetch/polyfill in my package.json and this solved the problem but it should be included by airbrake-js as a runtime dependency, not just in devDependencies

Also (maybe not related) I got this again:

can not report routes stats Error: route stat: sum <= 0
    at /home/menendez/git/indexing-service/node_modules/airbrake-js/dist/webpack:/airbrakeJs.Client/src/http_req/fetch.ts:49:27
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by hrdwdmrbl** [comment]
Are there tests for this module? `Error: Cannot find module 'cross-fetch'`
