### ISSUE TITLE
How to stub airbrake notify in tests?

### ISSUE THREAD

**Issue by Hirurg103** [airbrake/airbrake-js#539]
I am running mocha tests and some test cases check that airbrake is being notified correctly. After test suite I see the following stack trace: 

```
1 passing (298ms)

can not report routes stats Error: strconv.ParseInt: parsing "project_id": invalid syntax
    at /Users/username/Documents/projectname/node_modules/airbrake-js/dist/client.js:1979:27
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

I initialize airbrake the following way: 

```js
const AirbrakeClient = require('airbrake-js');
const config = require('lib/config');

const airbrake = new AirbrakeClient({
  projectId: config.airbrake.project_id,
  projectKey: config.airbrake.project_key,
  environment: `myappname_${process.env.NODE_ENV}`,
});

module.exports = airbrake;
```

How can I stub `airbrake.notify` in the test environment to stop notifying airbrake when running tests? 

Thanks!

**Comment by Hirurg103** [comment]
I tried to add 

```js
airbrake.addFilter((notice) => {
  if (process.env.NODE_ENV == 'test')
    return null;

  return notice;
});
```

but I still see the `strconv.ParseInt` error in tests

**Comment by Hirurg103** [comment]
Maybe there is a fake client which has the same interface as the production client which I can use in tests?

**Comment by vmihailenco** [comment]
No, you would have to write such stub yourself.

Overall it looks like the value in `config.airbrake.project_id` is not a project number.

**Comment by Hirurg103** [comment]
`can not report routes stats Error`

@vmihailenco seems like that it is trying to send route stats in tests and I need to stub request for route stats some way. Do you have any idea how can I do that?

**Comment by Hirurg103** [comment]
I was able to mock airbrake in tests with the following code:

```js
// fake_airbrake_client.js
const AirbrakeClient = require('airbrake-js');
fakeAirbrakeClient = new AirbrakeClient({
  projectId: 1,
  projectKey: 'key',
  environment: 'test',
});
fakeAirbrakeClient.notifyRequest = () => {};  // !!! NOTE THIS LINE !!!

module.exports = fakeAirbrakeClient;
```

then in the app test:

```js
// app_test.js
const fakeAirbrakeClient = require('./fake_airbrake_client');

describe('app', () => {
  beforeEach(() => {
    mockery.registerMock('lib/airbrake', fakeAirbrakeClient);
    this.app = require('../../app'); // Uses airbrake under the hood
    this.get = (url) => chai.request(this.app).get(url);
  });

  it('tests something', () => {
    // ..
  });
});
```
