### ISSUE TITLE
can not report routes stats Error: tdigest is missing

### ISSUE THREAD

**Issue by webdeveric** [airbrake/airbrake-js#547]
I'm getting lots of these errors in my terminal.

```shell
can not report routes stats Error: tdigest is missing
    at [...]/node_modules/airbrake-js/dist/client.js:1990:27
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**airbrake-js version:** 1.6.7
**Node version:** 10 (current LTS)
**Framework:** Next.js 8.1 (Express middleware)
**Client config:**
```js
const airbrake = new AirbrakeClient({
  projectId: process.env.AIRBRAKE_PROJECT_ID,
  projectKey: process.env.AIRBRAKE_PROJECT_KEY,
  environment: process.env.NODE_ENV,
});
```

**Comment by vmihailenco** [comment]
Please try v1.6.8
