### ISSUE TITLE
@airbrake/node does not have dependencies listed in published version

### ISSUE THREAD

**Issue by alexlaj** [airbrake/airbrake-js#580]
It seems that while both `error-stack-parser` and `tdigest` are listed as dependencies in `@airbrake/node`s `package.json` (https://github.com/airbrake/airbrake-js/blob/master/packages/node/package.json), they do not appear to be listed as dependencies in the published version (https://unpkg.com/browse/@airbrake/node@1.0.0-beta.1/package.json).

After installing `@airbrake/node` and setting it up, it will throw an error (for example)
```
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'error-stack-parser'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/alex_lajeunesse/src/testairbrakenode/node_modules/@airbrake/node/dist/airbrake.common.js:7:40)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```
unless you add `error-stack-parser` and `tdigest` as dependencies to your project. It would be nice if `@airbrake/node` listed these dependencies in the published version.

You can reproduce this by using the code from the express example here https://github.com/airbrake/airbrake-js/blob/master/packages/node/examples/express/app.js (I personally removed the `pg`-related items). Please let me know if any additional information would be helpful.

**Comment by vmihailenco** [comment]
It seems to be already fixed in master branch - https://github.com/airbrake/airbrake-js/blob/master/packages/node/package.json#L19-L20. I will publish the new version once it is ready.

**Comment by alexlaj** [comment]
Thank you @vmihailenco

**Comment by rcmgleite** [comment]
Is it published? I'm having the same issue here.

**Comment by vmihailenco** [comment]
Just pushed 1.0.0-beta.2.
