### ISSUE TITLE
Exception in production: can not report queries stats (socket hang up)

### ISSUE THREAD

**Issue by rbjarnason** [airbrake/airbrake-js#620]
I've recently upgraded to @airbrake/node and I'm getting those errors in our apps logs on production. Any ideas? 

Our apps are hosted on Heroku.

FetchError: request to https://api.airbrake.io/api/v5/projects/124117/queries-stats?key=XXXX failed, reason: socket hang up
    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:198:13)
    at ClientRequest.EventEmitter.emit (domain.js:448:20)
    at ClientRequest.req.emit (/app/node_modules/@airbrake/node/dist/instrumentation/https.js:19:29)
    at TLSSocket.socketOnEnd (_http_client.js:426:9)
    at TLSSocket.emit (events.js:203:15)
    at TLSSocket.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)Exception

**Comment by rbjarnason** [comment]
This is intermittent but still 15 errors in the past 24 hours and 94 since we launched the update a week ago.

**Comment by sgray** [comment]
Hi, @rbjarnason. Sorry for the delay. Are you still experiencing this issue?
