### ISSUE TITLE
Unable to use with Rollup, targeting ES modules

### ISSUE THREAD

**Issue by akauppi** [airbrake/airbrake-js#834]
# 🐞 bug report

### Affected Package

The issue is with `@airbrake/browser`. 

### Is this a regression?

I am new to Airbrake, so haven't tried this with previous versions.

### Description

I have a [project](https://github.com/akauppi/GroundLevel-es6-firebase-web) that builds a web app. Unlike most currently web apps, this one uses ES modules all the way to the browser. No traditional bundler involved.

When I build the production variant with Vite, things seem normal.

When I build it with Rollup directly, `@airbrake/browser` causes the following errors, and I get no beef. I haven't seen anything like this with other libraries:

```
$ npm run prod:build
...
> groundlevel-es6-firebase@0.0.1 _prod_rollup_build /Users/asko/Git/GroundLevel-es6-firebase-web
> rollup -c rollup.config.prod.js

src/init.prod-rollup.js → public/dist...
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
node_modules/@airbrake/browser/esm/notifier.js
1: var __extends = (this && this.__extends) || (function () {
                    ^
2:     var extendStatics = function (d, b) {
3:         extendStatics = Object.setPrototypeOf ||
...and 3 other occurrences
node_modules/@airbrake/browser/esm/base_notifier.js
1: var __assign = (this && this.__assign) || function () {
                   ^
2:     __assign = Object.assign || function(t) {
3:         for (var s, i = 1, n = arguments.length; i < n; i++) {
...and 1 other occurrence
node_modules/@airbrake/browser/esm/queries.js
1: var __assign = (this && this.__assign) || function () {
                   ^
2:     __assign = Object.assign || function(t) {
3:         for (var s, i = 1, n = arguments.length; i < n; i++) {
...and 1 other occurrence

...and 4 other files
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
toastify-js (imported by src/central.js)
toastify-js/src/toastify.css (imported by src/central.js)
error-stack-parser (imported by node_modules/@airbrake/browser/esm/processor/esp.js)
cross-fetch (imported by node_modules/@airbrake/browser/esm/http_req/fetch.js)
(!) Unused external imports
default imported from external module 'toastify-js' but never used
[!] (plugin prodIndex) TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at /Users/asko/Git/GroundLevel-es6-firebase-web/rollup.config.prod.js:149:27
    at Set.forEach (<anonymous>)
    at Object.generateBundle (/Users/asko/Git/GroundLevel-es6-firebase-web/rollup.config.prod.js:148:13)
    at /Users/asko/Git/GroundLevel-es6-firebase-web/node_modules/rollup/dist/shared/rollup.js:18616:25
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! groundlevel-es6-firebase@0.0.1 _prod_rollup_build: `rollup -c rollup.config.prod.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the groundlevel-es6-firebase@0.0.1 _prod_rollup_build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/asko/.npm/_logs/2020-09-11T12_20_23_336Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! groundlevel-es6-firebase@0.0.1 prod:build: `npm run _prod_rollup_build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the groundlevel-es6-firebase@0.0.1 prod:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/asko/.npm/_logs/2020-09-11T12_20_23_362Z-debug.log
```

The mentioned log files have: 

```
...
18 verbose stack Error: groundlevel-es6-firebase@0.0.1 _prod_rollup_build: `rollup -c rollup.config.prod.js`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
18 verbose stack     at EventEmitter.emit (events.js:314:20)
18 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:314:20)
18 verbose stack     at maybeClose (internal/child_process.js:1051:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
...
```

I will try to bring Airbrake in via a script tag, instead.

Maybe there is something wrong with the ES publishing of Airbrake? The behaviour is reproducible, but unfortunately I don't have the time to create a minimal reproduction case. Setting up my project takes ~15 minutes and does involve creating a Firebase account.

The commit to reproduce this is `c674c12..b366e7d`.

## 🔬 Minimal Reproduction

 https://gist.github.com/...

Sorry, no. See above.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**@airbrake/browser version:**
<pre><code>
1.4.1
</code></pre>

- Node 14.8.0
- Rollup 2.26.11
- macOS

**Anything else relevant?**

I find it weird how Rollup fails already in the build stage.

**Comment by akauppi** [comment]
Knock knock

**Comment by benjclark** [comment]
I think this is related to the issue I reported as well: https://github.com/airbrake/airbrake-js/issues/832

I also see the warning `The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten` in the console with my issue.

**Comment by kyrylo** [comment]
Sorry, we couldn't resolve this in a timely fashion. It's a bit hard to reproduce your issue now. We've released many versions of airbrake-js already, and perhaps this issue was inherently resolved. If not, I'd be happy to take a look.
